# Generated by Django 4.2.30 on 2026-05-25 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('rule_name', models.CharField(help_text='Machine-readable rule identifier', max_length=100)),
                ('message', models.TextField(help_text='Human-readable description of the issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='normalization.emissionrecord')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['emission_record', 'severity'], name='validation__emissio_711ed3_idx')],
            },
        ),
    ]
