# Generated by Django 4.2.30 on 2026-05-26 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(help_text='Machine-readable rule identifier', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold', models.JSONField(blank=True, default=dict, help_text="Rule-specific configuration, e.g. {'max_value': 100000}")),
                ('source_types', models.JSONField(blank=True, default=list, help_text="Which source types this rule applies to, e.g. ['sap', 'utility']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['rule_name'],
                'unique_together': {('organization', 'rule_name')},
            },
        ),
    ]
