# Generated by Django 4.2.30 on 2026-05-25 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct'), ('scope_2', 'Scope 2 — Indirect (Energy)'), ('scope_3', 'Scope 3 — Indirect (Value Chain)')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('activity_value', models.DecimalField(blank=True, decimal_places=4, help_text='Original measured value', max_digits=16, null=True)),
                ('activity_unit', models.CharField(blank=True, default='', max_length=50)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, help_text='Value after unit normalization', max_digits=16, null=True)),
                ('normalized_unit', models.CharField(blank=True, default='', max_length=50)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional source-specific data')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
