# Generated by Django 4.2.30 on 2026-05-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalization', '0001_initial'),
        ('organizations', '0001_initial'),
        ('ingestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status'], name='normalizati_organiz_79324c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'source_type'], name='normalizati_organiz_0b5f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope'], name='normalizati_organiz_ac54af_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['reporting_date'], name='normalizati_reporti_06a975_idx'),
        ),
    ]
