# Generated by Django 4.2.30 on 2026-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked records cannot be edited or have status changed.'),
        ),
    ]
