# Generated by Django 4.2.30 on 2026-05-25 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Action identifier (e.g. upload_started, record_approved)', max_length=100)),
                ('entity_type', models.CharField(help_text='Model name of the affected entity', max_length=100)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=255)),
                ('previous_value', models.JSONField(blank=True, help_text='State before the action', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='State after the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
